mariadb:
  image: eventuateio/eventuate-mariadb:0.9.0.RC3
  ports:
    - 3306:3306
  environment:
    - MYSQL_ROOT_PASSWORD=rootpassword
    - MYSQL_USER=mysqluser
    - MYSQL_PASSWORD=mysqlpw

zookeeper:
  image: eventuateio/eventuate-zookeeper:0.9.0.RC3
  ports:
    - 2181:2181
    - 2888:2888
    - 3888:3888


kafka:
  image: eventuateio/eventuate-kafka:0.9.0.RC2
  ports:
    - 9092:9092
  links:
    - zookeeper
  environment:
    - ADVERTISED_HOST_NAME=${DOCKER_HOST_IP}
    - KAFKA_HEAP_OPTS=-Xmx320m -Xms320m
    - ZOOKEEPER_SERVERS=zookeeper:2181

activemq:
  image: webcenter/activemq:5.14.3
  ports:
    - 8161:8161
    - 61616:61616
    - 61613:61613
    - 1883:1883
    - 61614:61614

rabbitmq:
  image: eventuateio/eventuate-rabbitmq:0.3.0.RELEASE
  ports:
    - 5672:5672

redis:
  image: redis:5.0.3
  ports:
    - 6379:6379
