zookeeper:
  image: eventuateio/eventuate-zookeeper:0.9.0.RC3
  ports:
    - 2181:2181
    - 2888:2888
    - 3888:3888


kafka:
  image: eventuateio/eventuate-kafka:0.9.0.RC2
  ports:
    - 9092:9092
  links:
    - zookeeper
  environment:
    - ADVERTISED_HOST_NAME=${DOCKER_HOST_IP}
    - KAFKA_HEAP_OPTS=-Xmx320m -Xms320m
    - ZOOKEEPER_SERVERS=zookeeper:2181

mssql:
  image: eventuateio/eventuate-mssql:0.9.0.RC3
  ports:
    - 1433:1433
  environment:
    SA_PASSWORD: Eventuate123!
    ACCEPT_EULA: Y
