version: 2
jobs:
  build:
    machine: true
    working_directory: ~/eventuate-cdc
    steps:
      - checkout
      - restore_cache:
          key: eventuate-cdc-{{ checksum "gradle.properties" }}
      - run: TERM=dumb ./gradlew testClasses
      - save_cache:
          paths:
            - ~/.gradle
          key: eventuate-cdc-{{ checksum "gradle.properties" }}
      - run: TERM=dumb ./scripts/build-and-test-mysql.sh
      - run:
          name: Save test results
          command: ./scripts/save-containers-and-tests.sh
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
      - store_artifacts:
          path: ~/container-logs
  build-and-test-mysql-migration:
    machine: true
    working_directory: ~/eventuate-cdc
    steps:
      - checkout
      - restore_cache:
          key: eventuate-cdc-{{ checksum "gradle.properties" }}
      - run: TERM=dumb ./gradlew testClasses
      - save_cache:
          paths:
            - ~/.gradle
          key: eventuate-cdc-{{ checksum "gradle.properties" }}
      - run: TERM=dumb ./scripts/build-and-test-mysql-migration.sh
      - run:
          name: Save test results
          command: ./scripts/save-containers-and-tests.sh
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
      - store_artifacts:
          path: ~/container-logs
  build-mariadb:
    machine: true
    working_directory: ~/eventuate-cdc
    steps:
      - checkout
      - restore_cache:
          key: eventuate-cdc-{{ checksum "gradle.properties" }}
      - run: TERM=dumb ./gradlew testClasses
      - save_cache:
          paths:
            - ~/.gradle
          key: eventuate-cdc-{{ checksum "gradle.properties" }}
      - run: TERM=dumb ./scripts/build-and-test-mariadb.sh
      - run:
          name: Save test results
          command: ./scripts/save-containers-and-tests.sh
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
      - store_artifacts:
          path: ~/container-logs
  build-postgres-wal:
    machine: true
    working_directory: ~/eventuate-cdc
    steps:
      - checkout
      - restore_cache:
          key: eventuate-cdc-{{ checksum "gradle.properties" }}
      - run: TERM=dumb ./scripts/build-and-test-postgres-wal.sh
      - run:
          name: Save test results
          command: ./scripts/save-containers-and-tests.sh
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
      - store_artifacts:
          path: ~/container-logs
  build-mssql-polling:
    machine: true
    working_directory: ~/eventuate-cdc
    steps:
      - checkout
      - restore_cache:
          key: eventuate-cdc-{{ checksum "gradle.properties" }}
      - run: TERM=dumb ./scripts/build-and-test-mssql-polling.sh
      - run:
          name: Save test results
          command: ./scripts/save-containers-and-tests.sh
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
      - store_artifacts:
          path: ~/container-logs
  build-postgres-polling:
    machine: true
    working_directory: ~/eventuate-cdc
    steps:
      - checkout
      - restore_cache:
          key: eventuate-cdc-{{ checksum "gradle.properties" }}
      - run: TERM=dumb ./scripts/build-and-test-postgres-polling.sh
      - run:
          name: Save test results
          command: ./scripts/save-containers-and-tests.sh
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
      - store_artifacts:
          path: ~/container-logs
  build-eventuate-local-cdc-mysql:
    machine: true
    working_directory: ~/eventuate-cdc
    steps:
      - checkout
      - restore_cache:
          key: eventuate-cdc-{{ checksum "gradle.properties" }}
      - run: TERM=dumb ./scripts/build-and-test-all-eventuate-local-cdc-mysql-binlog.sh
      - run:
          name: Save test results
          command: ./scripts/save-containers-and-tests.sh
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
      - store_artifacts:
          path: ~/container-logs
  build-eventuate-local-cdc-mariadb:
    machine: true
    working_directory: ~/eventuate-cdc
    steps:
      - checkout
      - restore_cache:
          key: eventuate-cdc-{{ checksum "gradle.properties" }}
      - run: TERM=dumb ./scripts/build-and-test-all-eventuate-local-cdc-mariadb-binlog.sh
      - run:
          name: Save test results
          command: ./scripts/save-containers-and-tests.sh
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
      - store_artifacts:
          path: ~/container-logs
  build-eventuate-local-cdc-postgres-polling:
    machine: true
    working_directory: ~/eventuate-cdc
    steps:
      - checkout
      - restore_cache:
          key: eventuate-cdc-{{ checksum "gradle.properties" }}
      - run: TERM=dumb ./scripts/build-and-test-all-eventuate-local-cdc-postgres-polling.sh
      - run:
          name: Save test results
          command: ./scripts/save-containers-and-tests.sh
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
      - store_artifacts:
          path: ~/container-logs
  build-eventuate-local-cdc-postgres-wal:
    machine: true
    working_directory: ~/eventuate-cdc
    steps:
      - checkout
      - restore_cache:
          key: eventuate-cdc-{{ checksum "gradle.properties" }}
      - run: TERM=dumb ./scripts/build-and-test-all-eventuate-local-cdc-postgres-wal.sh
      - run:
          name: Save test results
          command: ./scripts/save-containers-and-tests.sh
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
      - store_artifacts:
          path: ~/container-logs
  build-eventuate-tram-cdc-mysql:
    machine: true
    working_directory: ~/eventuate-cdc
    steps:
      - checkout
      - restore_cache:
          key: eventuate-cdc-{{ checksum "gradle.properties" }}
      - run: TERM=dumb ./scripts/build-and-test-all-tram-cdc-mysql-binlog.sh
      - run:
          name: Save test results
          command: ./scripts/save-containers-and-tests.sh
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
      - store_artifacts:
          path: ~/container-logs
  build-eventuate-tram-cdc-postgres-polling:
    machine: true
    working_directory: ~/eventuate-cdc
    steps:
      - checkout
      - restore_cache:
          key: eventuate-cdc-{{ checksum "gradle.properties" }}
      - run: TERM=dumb ./scripts/build-and-test-all-tram-cdc-postgres-polling.sh
      - run:
          name: Save test results
          command: ./scripts/save-containers-and-tests.sh
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
      - store_artifacts:
          path: ~/container-logs
  build-eventuate-tram-cdc-postgres-wal:
    machine: true
    working_directory: ~/eventuate-cdc
    steps:
      - checkout
      - restore_cache:
          key: eventuate-cdc-{{ checksum "gradle.properties" }}
      - run: TERM=dumb ./scripts/build-and-test-all-tram-cdc-postgres-wal.sh
      - run:
          name: Save test results
          command: ./scripts/save-containers-and-tests.sh
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
      - store_artifacts:
          path: ~/container-logs
  build-eventuate-tram-cdc-mssql-polling:
    machine: true
    working_directory: ~/eventuate-cdc
    steps:
      - checkout
      - restore_cache:
          key: eventuate-cdc-{{ checksum "gradle.properties" }}
      - run: TERM=dumb ./scripts/build-and-test-all-tram-cdc-mssql-polling.sh
      - run:
          name: Save test results
          command: ./scripts/save-containers-and-tests.sh
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
      - store_artifacts:
          path: ~/container-logs
  build-cdc-unified:
    machine: true
    working_directory: ~/eventuate-cdc
    steps:
      - checkout
      - restore_cache:
          key: eventuate-cdc-{{ checksum "gradle.properties" }}
      - run: TERM=dumb ./scripts/build-and-test-all-cdc-unified.sh
      - run:
          name: Save test results
          command: ./scripts/save-containers-and-tests.sh
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
      - store_artifacts:
          path: ~/container-logs
  publish:
    machine: true
    working_directory: ~/eventuate-cdc
    steps:
      - checkout
      - restore_cache:
          key: eventuate-cdc-{{ checksum "gradle.properties" }}
      - run: TERM=dumb ./gradlew testClasses
      - save_cache:
          paths:
            - ~/.gradle
          key: eventuate-cdc-{{ checksum "gradle.properties" }}
      - run:
          name: Publish artifacts
          command: |
            TERM=dumb ./scripts/deploy-artifacts.sh
          when: on_success
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - build-mariadb
      - build-and-test-mysql-migration
      - build-postgres-wal:
          requires:
            - build
      - build-mssql-polling:
          requires:
            - build
      - build-postgres-polling:
          requires:
            - build
      - build-eventuate-local-cdc-mysql:
          requires:
            - build
      - build-eventuate-local-cdc-mariadb:
          requires:
            - build-mariadb
      - build-eventuate-local-cdc-postgres-wal:
          requires:
            - build-postgres-wal
      - build-eventuate-local-cdc-postgres-polling:
          requires:
            - build
      - build-eventuate-tram-cdc-mysql:
          requires:
            - build
      - build-eventuate-tram-cdc-postgres-polling:
          requires:
            - build
      - build-eventuate-tram-cdc-postgres-wal:
          requires:
            - build
      - build-eventuate-tram-cdc-mssql-polling:
          requires:
            - build
      - build-cdc-unified:
          requires:
            - build-eventuate-local-cdc-mysql
            - build-eventuate-local-cdc-mariadb
            - build-eventuate-local-cdc-postgres-wal
            - build-eventuate-local-cdc-postgres-polling
            - build-eventuate-tram-cdc-mysql
            - build-eventuate-tram-cdc-postgres-polling
            - build-eventuate-tram-cdc-postgres-wal
            - build-eventuate-tram-cdc-mssql-polling
      - publish:
          requires:
            - build-cdc-unified
